name: nclaw
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - scipy
  - pyvista
  - hydra-core
  - trimesh
  - einops
  - tqdm
  - psutil
  - tensorboard
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/nightly/cu128
      - torch --pre
      - numpy<2.0
      - warp-lang==0.10.1